package com.kirkukhealth.poster.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * User Profile Settings for Health Promotion Units
 * إعدادات الملف الشخصي لوحدات تعزيز الصحة
 */
@Entity
@Table(name = "user_profiles")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserProfile {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(nullable = false, unique = true)
    private String userId; // Foreign key to User table

    /**
     * Health Center Name
     * اسم المركز الصحي
     */
    @Column(name = "health_center_name", length = 200)
    private String healthCenterName;

    /**
     * Manager Name of Health Promotion Unit
     * اسم مدير وحدة تعزيز الصحة
     */
    @Column(name = "manager_name", length = 150)
    private String managerName;

    /**
     * Directorate Name (Default: Kirkuk Health Directorate - First Sector)
     * اسم المديرية (افتراضي: دائرة صحة كركوك – قطاع كركوك الأول)
     */
    @Column(name = "directorate_name", length = 200)
    @Builder.Default
    private String directorateName = "دائرة صحة كركوك – قطاع كركوك الأول";

    /**
     * Logo file path (stored in src/main/resources/static/assets/logos/)
     * Default: logo.jpg (FIXED official logo for all posters)
     * مسار ملف الشعار (محفوظ في src/main/resources/static/assets/logos/)
     * افتراضي: logo.jpg (الشعار الرسمي الثابت لجميع البوسترات)
     */
    @Column(name = "logo_path", length = 500)
    @Builder.Default
    private String logoPath = "logo.jpg"; // Fixed official logo

    /**
     * Whether to show verification badge on posters
     * إظهار شارة التحقق على البوسترات
     */
    @Column(name = "show_verification_badge")
    @Builder.Default
    private Boolean showVerificationBadge = true;

    /**
     * Count of posters generated by this health center
     * عدد البوسترات المولدة من قبل هذا المركز الصحي
     */
    @Column(name = "posters_generated_count")
    @Builder.Default
    private Integer postersGeneratedCount = 0;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}

