-- ============================================================================
-- Database Migration V2: Add posters_generated_count column
-- ============================================================================
-- إضافة عمود عدد البوسترات المولدة
-- Add column to track number of posters generated by each health center
--
-- Purpose: Enable statistics and reporting functionality
-- الغرض: تمكين ميزة الإحصائيات والتقارير
--
-- This column is automatically incremented when:
-- - A regular poster is generated (POST /api/posters/generate)
-- - A welcome poster is generated (GET /api/posters/welcome/{centerId})
--
-- Used in:
-- - Statistics endpoint (GET /api/admin/statistics)
-- - CSV export (GET /api/admin/statistics/export)
-- ============================================================================

-- Add column if it doesn't exist
-- إضافة العمود إذا لم يكن موجوداً
ALTER TABLE user_profiles 
ADD COLUMN IF NOT EXISTS posters_generated_count INTEGER DEFAULT 0;

-- Update existing records to have 0 if NULL
-- تحديث السجلات الموجودة لتكون 0 إذا كانت NULL
UPDATE user_profiles 
SET posters_generated_count = 0 
WHERE posters_generated_count IS NULL;

-- Add comment for documentation
-- إضافة تعليق للتوثيق
COMMENT ON COLUMN user_profiles.posters_generated_count IS 'عدد البوسترات المولدة من قبل المركز الصحي | Count of posters generated by this health center (auto-incremented)';

